---
- name: Restart clickhouse-server service
  systemd:
    name: "clickhouse-server"
    state: restarted
    daemon_reload: yes
  when:
    - clickhouse_service_state == 'started'
    - clickhouse_service_restart_on_config_change